Regisztracios oldal
alxkovacs/Kovacs_Alex_Szakdolgozat pull request #10
Opened 2023-11-30 14:39 UTC by alxkovacs

2023-11-30 14:45 UTC, alxkovacs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Regisztráció képernyő design és navigáció](https://trello.com/c/3Vp9EnQ7/22-regisztr%C3%A1ci%C3%B3-k%C3%A9perny%C5%91-design-%C3%A9s-navig%C3%A1ci%C3%B3)

2023-11-30 14:46 UTC, alxkovacs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Regisztráció üzleti logika](https://trello.com/c/xwOv3p1F/35-regisztr%C3%A1ci%C3%B3-%C3%BCzleti-logika)

2023-12-04 11:19 UTC, Vini1424 commented on application/lib/model/user_model.dart
> +  // További szükséges mezők...
Kérlek ilyen kommenteket ne hagyjunk benne a kódban. Szedjük ki.

2023-12-04 11:20 UTC, Vini1424 commented on application/lib/model/user_model.dart
> +  // Firestore dokumentumból történő létrehozás
Kérlek magyarázó kommentek se maradjanak. A kódnak önmagának olyannak kell lennie, hogy olvasható legyen és érthető.

2023-12-04 11:27 UTC, Vini1424 commented on application/lib/model/user_model.dart
> +  Map<String, dynamic> toMap() {
A függvény neve mindig valami akció vagy ige ami megmondja, hogy a működés során hol használjuk. Az ige stimmel, de a toMap nagyon általános név. Ezt a függvényt mindig ott fogod használni feltételezésem szerint mikor felküldöd firestore-ba az adatot, tehát ennek a függvénynek lehetne az a neve, hogy convertToFirestoreFormat()

2023-12-04 11:35 UTC, Vini1424 commented on application/lib/utils/translation_en.dart
> +
Kérlek az üres sort, aminek nincs kifejezetten célja töröljük.

2023-12-04 11:41 UTC, Vini1424 commented on application/lib/view/widgets/auth_image_widget.dart
> +      width: 400,
Nem szerencsés fix méretet adni a képeknek. Különböző képernyőkhöz is alkalmazkodnia kell és a beégetett méret ezt nem segíti elő. Ilyenkor inkább FractionallySizedBox widgetet használjunk vagy Expanded widgetet flex értékekkel.
https://api.flutter.dev/flutter/widgets/FractionallySizedBox-class.html
https://api.flutter.dev/flutter/widgets/Expanded-class.html

2023-12-04 11:51 UTC, Vini1424 commented on application/lib/view_model/sign_up_view_model.dart
> +  Future<bool> submitSignUp(String enteredFirstName, String enteredEmail,
A Firebase authentikáció és ez a függvény nem a viewmodel felelősségi köre. A viewmodel feladata, hogy az üzleti logikát kezelje, tehát tudja, hogy mikor melyik funkciót kell végrehajtani és a funkciókhoz melyik service-t kell meghívni. Amit küldtem minta, ott is látszódik, hogy van még egy plusz service layer. Legyen egy AuthenticationService.dart és ez a service legyen felelős az authentikációért. Ez a submitSignUp függvény pedig hívja az AuthenticationService megfelelő függvényét. Miért csináljuk ezt így? Azért hogy bármelyik réteg könnyen cserélhető legyen. Tehát ha egyszer úgy dönt az ember hogy firebase helyett másik adatbázis kezelőt használ, akkor ne kelljen az összes viewmodelben hosszasan újra kódolni, hanem csak a service fileokat kicseréljük új service fileokra, amikben implementálva vannak a szükséges függvények, és a viewmodel az új servicet filet hívja be.

2023-12-04 11:56 UTC, Vini1424 commented on application/lib/view_model/sign_up_view_model.dart
> +    if (value == null || value.trim().length < 6) {
Van egy null coalescing operator, ami a legtöbb programozási nyelvben meg van valósítva. Ezzel a null ellenőrzést hatékonyabban lehet kezelni sokszor. Itt például az összetett || kifejezés helyett, le lehet egyszerűbben is írni: 
(value?.trim()?.length ?? 0) < 6

Ebben az esetben ha a kérdőjel előtti kifejezés null, akkor a dupla kérdőjel utáni kifejezést adja vissza automatikusan. 

https://dart.dev/codelabs/null-safety#exercise-null-coalescing-operators

2023-12-04 12:01 UTC, Vini1424 commented on application/lib/view_model/sign_up_view_model.dart
> +    if (value == null || value.trim().length < 3) {
Egyszerű if szerkezeteknél, tudod használni az inline if szerkezetet is ha szeretnéd. Tehát ezt a függvényt így is le tudjuk írni: 
`return (value?.trim()?.length ?? 0) < 3 ? TranslationEN.firstNameValidator : String.empty`

Sose szerencsés egyébként null-t visszaadni. Nagyon könnyen okozhat hibát. Próbáljuk meg kerülni és pl inkább üres stringet visszaadni vagy máshogy implementálni a logikát ahol csak tudjuk.

2023-12-04 12:05 UTC, Vini1424 commented on application/lib/view/screens/sign_up_screen.dart
> +    final viewModel = ref.watch(signUpViewModelProvider);
A viewmodel használatához használjuk a Provider packaget, ahogy a példában is volt amit küldtem. Így nem kell külön implemetálni egyéni providereket, mint amit most tettél. 
így kell kinéznie a véglegesnek: `final signUpScreenViewModel = Provider.of<signUpScreenViewModel>(context);`

https://nureddineraslan.medium.com/understanding-state-management-with-provider-in-flut-e74e0b9e49d9

2023-12-04 12:14 UTC, Vini1424 requested changes
Kérlek rebaseljünk majd a masterre.

2023-12-06 23:21 UTC, alxkovacs commented
![signup_screen_iphone_se](https://github.com/alxkovacs/Kovacs_Alex_Szakdolgozat/assets/123123690/ffc2e029-6407-4e17-a8f9-f2543bedeb02)
![signup_screen_note_20_ultra](https://github.com/alxkovacs/Kovacs_Alex_Szakdolgozat/assets/123123690/a2baf150-6765-4f3b-8136-2104bcc4b02b)

2023-12-07 09:20 UTC, alxkovacs commented
> Kérlek rebaseljünk majd a masterre.

Ez még masterről lett létrehozva.

2023-12-07 09:23 UTC, alxkovacs commented
> Kérlek rebaseljünk majd a masterre.

Nem tudtam rebaselni, mert masterről lett létrehozva.

2023-12-07 15:01 UTC, Vini1424 commented on application/lib/view/screens/base_screen.dart
> +        title: const Text('Főoldal'),
Kérlek a stringet emeljük ki.

2023-12-07 15:01 UTC, Vini1424 commented on application/lib/view/screens/base_screen.dart
> +        child: Text('Hello'),
Kérlek emeljük ki itt is.

2023-12-07 15:02 UTC, Vini1424 commented on application/lib/view/screens/login_screen.dart
> +        title: const Text('Bejelentkezés'),
Kérlek a stringet emeljük ki.

2023-12-07 15:02 UTC, Vini1424 commented on application/lib/view/screens/login_screen.dart
> +        child: Text('Hello'),
Kérlek a stringet emeljük ki.

2023-12-07 15:21 UTC, Vini1424 commented on application/lib/view/screens/sign_up_screen.dart
> +    final screenWidth = MediaQuery.of(context).size.width;
A MediaQuery használatát próbáljuk elkerülni. Miért: a mediaquery osztály több device-al kapcsolatos információra fel van iratkozva. Úgy kell elképzelni mint ahogy mi a changenotifier-t használjuk. Amikor a teljes mediaquery-t behúzod a .of(context) függvénnyel, akkor az azt fogja eredményezni, hogy bármi megváltozik a készülék beállításaiban, az leszól a mediaquerynek, aki miatt újra lesz renderelve az oldal. Jó példa erre, hogy mondjuk alkalmazás használata közben feljebb húzod a fényerőt. Emiatt még nem kéne újra renderelni, de a mediaquery fel van iratkozva és emiatt triggerelődni fog. 
Ennek elkerülésére két lehetőség van: egyrész részesítsük előnyben inkább az Expanded és a FractionallySizedBox widgeteket. Meg kell tanulni reszponzív vidgetekben gondolkodni mikor egy képernyőt teszünk össze. 
A másik elkerülési lehetőség, hogy nem az összes mediaquery által figyelt változóra iratkozunk fel, hanem csak egy részére, tehát pl size esetén: MediaQuery.sizeOf(context).height

2023-12-07 15:32 UTC, Vini1424 commented on application/lib/view/screens/sign_up_screen.dart
> +  var _enteredFirstName = '';
Az MVVM model lényege, hogy a view nem tartalmaz lehetőleg semmilyen komplex logikát. Neki csak annyi a feladata, hogy van egy Model objektuma, ahonnan felolvassa az adatokat. A model objektum változásait és kezelését pedig a viewmodel végzi. Na most, itt a Model az konkrétan a UserModel. Tehát neked ezeket az adattagokat közvetlenül oda kell tárolnod, nem pedig letárolni itt a view-ban is és plusz még a viewmodelben is. A célunk az egységbe zárás és az hogy a logikailag egybefüggő részek kezelése egy helyen történjen. 

Kérlek ezt módosítsuk. Amik küldtem korábban példát "flutter-layer-example.txt" ott jól látszódik, hogy mire gondolok.

2023-12-07 16:50 UTC, Vini1424 approved these changes

2023-12-07 16:56 UTC, merged