Bejelentkezés
alxkovacs/Kovacs_Alex_Szakdolgozat pull request #11
Opened 2023-12-01 00:48 UTC by alxkovacs

2023-12-01 00:52 UTC, alxkovacs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bejelentkezés képernyő design és navigáció](https://trello.com/c/jkRcqhtZ/23-bejelentkez%C3%A9s-k%C3%A9perny%C5%91-design-%C3%A9s-navig%C3%A1ci%C3%B3)

2023-12-01 00:52 UTC, alxkovacs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bejelentkezés üzleti logika](https://trello.com/c/6tcxGuVG/36-bejelentkez%C3%A9s-%C3%BCzleti-logika)

2023-12-07 10:09 UTC, alxkovacs commented
![login_screen_android](https://github.com/alxkovacs/Kovacs_Alex_Szakdolgozat/assets/123123690/f3b6be4a-6b79-4ffa-9811-11c0fdf51be7)
![login_screen_ios](https://github.com/alxkovacs/Kovacs_Alex_Szakdolgozat/assets/123123690/2914e96e-7f25-4c21-844c-40aa99def864)

2023-12-08 00:03 UTC, Vini1424 requested changes
Szuper lett. Még a skypeon megbeszélt UserDTO készüljön el. Amit kérlek az egyel korábbi képernyőre is alkalmazzunk. :)

2023-12-08 09:14 UTC, Vini1424 commented on application/lib/service/authentication_service.dart
> +      UserDTO userDTO = userModel.toUserDTO();
Ennek a konverziónak egy réteggel feljebb meg kell történnie. Az a szabály, hogy egy réteg csak arról az objektumról tud, ami neki kell és amit az ő általa hívott rétegek várnak. Az uthentication service UserDTO-t vár. Az ő általa hívott réteg már maga a firebase, aki json-t vár.

2023-12-08 09:20 UTC, Vini1424 approved these changes

2023-12-08 09:21 UTC, merged