Base screen, BottomNavigationBar
alxkovacs/Kovacs_Alex_Szakdolgozat pull request #12
Opened 2023-12-01 00:49 UTC by alxkovacs

2023-12-01 00:51 UTC, alxkovacs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Base képernyő, BottomNavigationBar](https://trello.com/c/X7RvylO9/61-base-k%C3%A9perny%C5%91-bottomnavigationbar)

2023-12-07 13:03 UTC, alxkovacs commented
![base_screen_android](https://github.com/alxkovacs/Kovacs_Alex_Szakdolgozat/assets/123123690/53664f84-946c-480a-81e8-5d6ad2a92ee5)
![base_screen_ios](https://github.com/alxkovacs/Kovacs_Alex_Szakdolgozat/assets/123123690/3745dd12-535b-4630-a3d9-b937e3af9a19)

2023-12-08 09:23 UTC, Vini1424 requested changes
jöhet a rebase és self review

2023-12-08 10:26 UTC, Vini1424 commented on application/lib/view_model/base_screen_view_model.dart
> +        return Padding(
Ezt az egyéni widgetet jól ki lehet emelni. A viewmodelben nem szerencsés ilyen hosszú widget kód, mert alapvetően szeparálni akarjuk a UI kódokat és a logikai kódokat, ahogy a view és viewmodel is szeparálódik. Kérlek a widgets mappába kerüljön egy új widget a megfelelő névvel. Úgy ahogy pl a CustomCircularProgressIndicator widgeted is létrejött.

2023-12-08 10:51 UTC, Vini1424 commented on application/lib/view/widgets/custom_bottom_sheet_scaffold.dart
> +class CustomBottomSheetScaffold extends StatelessWidget {
A Widget neve célszerű ha elmondja azt is, hogy mi a célja. Pl LoadingIndicator, HomeScreen, BottomNavigation, stb. Ebből a névből egyenlőre csak az látszik, hogy valaminek az alján egy sheet. Jobb lehet pl a CustomNavigationSheet.

2023-12-08 11:36 UTC, Vini1424 approved these changes

2023-12-08 11:37 UTC, merged