Főoldal
alxkovacs/Kovacs_Alex_Szakdolgozat pull request #13
Opened 2023-12-01 00:50 UTC by alxkovacs

2023-12-01 00:51 UTC, alxkovacs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Főoldal képernyő design és navigáció](https://trello.com/c/tJovrJWm/24-f%C5%91oldal-k%C3%A9perny%C5%91-design-%C3%A9s-navig%C3%A1ci%C3%B3)

2023-12-01 00:51 UTC, alxkovacs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Főoldal üzleti logika](https://trello.com/c/BZZWUjdJ/37-f%C5%91oldal-%C3%BCzleti-logika)

2023-12-07 13:08 UTC, alxkovacs commented
![home_screen_android](https://github.com/alxkovacs/Kovacs_Alex_Szakdolgozat/assets/123123690/733d3021-b26d-470a-9c0c-2ae6c1819f16)
![home_screen_ios](https://github.com/alxkovacs/Kovacs_Alex_Szakdolgozat/assets/123123690/d4f35d5a-7c66-4015-aaa6-03ac5386fd7b)

2023-12-08 12:07 UTC, Vini1424 requested changes
mehet a rebase és a self review

2023-12-08 22:48 UTC, Vini1424 commented on application/lib/view/screens/home_screen.dart
> +                      fontSize: MediaQuery.of(context).textScaleFactor * 30,
Abban az esetben, ha mindenképp szükség van a MediaQuery-re, akkor ne az összes attributumra iratkozzunk fel a MediaQuery.of() függvénnyel, mert így minden változásra frissülni fog a képernyő, még arra is ha fényerőt állít a user. Ilyenkor használjuk konkrétan azt, amire szükségünk van, ebben az esetben MediaQuery.textScaleFactorOf()

2023-12-08 22:54 UTC, Vini1424 commented on application/lib/view/widgets/savings_card.dart
> +    double padding = screenWidth > 600 ? 24 : 12;
Itt mindenképp kell a mediaquery? Fordított megközelítéssel nem lehet a Card-ot egy FractionallySizedBox-ba csomagolni, szélességet, magasságot állítani és tenni rá egy fix padding-et?

2023-12-08 22:59 UTC, Vini1424 commented on application/lib/view_model/home_screen_view_model.dart
> +  List<Map<String, dynamic>> menu = [
A statikusan indexelt listákkal óvatosan. Könnyen nullpointer exception vagy index out of range lehet a használatukból. Statikus indexelés azt értem, hogy a view ahol használod ott úgy hivatkozol rá, hogy menu[0] és menu[1]. Ebben az esetben lehet szerencsésebb lenne, ha ezt a két navigációt ugyan úgy kezelnénk, mint a többit is. Van valami oka annak, hogy ez listába lett téve?

2023-12-09 11:49 UTC, Vini1424 approved these changes

2023-12-09 11:50 UTC, merged