Termékek, keresés
alxkovacs/Kovacs_Alex_Szakdolgozat pull request #14
Opened 2023-12-01 00:50 UTC by alxkovacs

2023-12-01 00:52 UTC, alxkovacs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Termékek képernyő design és navigáció](https://trello.com/c/vZipy7SF/25-term%C3%A9kek-k%C3%A9perny%C5%91-design-%C3%A9s-navig%C3%A1ci%C3%B3)

2023-12-01 00:52 UTC, alxkovacs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Termékek üzleti logika](https://trello.com/c/403gwZR1/38-term%C3%A9kek-%C3%BCzleti-logika)

2023-12-07 15:07 UTC, alxkovacs commented
![products_screen_android](https://github.com/alxkovacs/Kovacs_Alex_Szakdolgozat/assets/123123690/28ac70e6-5b29-4a17-bae6-fdf3510d8ebe)
![products_screen_ios](https://github.com/alxkovacs/Kovacs_Alex_Szakdolgozat/assets/123123690/a3df8656-5fc3-4654-a5c1-53d8fe561b36)

2023-12-09 11:52 UTC, Vini1424 requested changes
mehet a rebase és a self review

2023-12-09 13:42 UTC, Vini1424 commented on application/lib/service/products_screen_service.dart
> +  Stream<List<ProductDTO>> fetchProducts(String searchTerm) {
A fetchProduct nagyon általános kifejezés, itt valójában az történik hogy keresési feltétel alapján le vannak szűrve a product-ok. Ha lenne egy olyan lekérdezésed, ami lekéri az összes productot, akár annak is lehetne a neve fetchProduct. Itt talán job a fetchProductByName

2023-12-09 13:53 UTC, Vini1424 commented on application/lib/view/screens/products_screen.dart
> +              controller: _searchController,
Van annak külön célja, hogy ki lett emelve változóba a TextEditingController ? Használjuk több helyen is ezen a kódon belül?

2023-12-09 14:06 UTC, Vini1424 commented on application/lib/view/widgets/custom_search_bar.dart
> +  final ProductsScreenViewModel viewModel;
Egy ViewModel egy View-hoz tartozik. Azért nem jó taktika, ha megosztod a viewmodeleket a view-k között, mert nem lesz egyértelmű, hogy éppen melyik view hívta a változtatásokat és mi miért történt. 
Ha arra van szükséged, hogy egy Widget egy külső viewmodelben lévő változót tudjon módosítani, mint itt a searchTerm-et, akkor erre van egy jobb taktika. 
Az onChanged függvényt várja a CustomSearchBar bemenő paraméterként. Szóval legyen egy adattagja a CustomSearchBar-nak: 
`final VoidCallback updateFunction; `
 Amikor pedig a CustomSearchBar-t beágyazod a product screenen, akkor 
`CustomSearchBar(updateFunction: viewModel.updateSearchTerm)` 
() nélkül, mert nem meghívni akarjuk az updateSearchTerm függvényt, hanem átadni.
A product screenen pedig hozzáférsz a viewModel-hez úgyhogy a viewmodelben legyen egy függvény:
`void updateSerachTerm(String value) {
        searchTerm = value;
      }`

2023-12-09 14:08 UTC, Vini1424 commented on application/lib/view/widgets/product_card.dart
> +    final productsScreenviewModel =
Itt is érvényes az , hogy ez a widget nem szabad hozzáférjen egy másik screen viewmodeljéhez. Vagy legyen itt simán meghívva a navigation függvény, vagy legyen saját viewmodelje.

2023-12-09 14:10 UTC, Vini1424 commented on application/lib/view_model/products_screen_view_model.dart
> +    fetchProducts();
A notifyListeners így kétszer fog meghívódni, tehát kétszer fog felfrissülni a képernyő. Ez felesleges renderelés lesz. Inkább azt ajánlom, hogy a fetchProducts függvény végén ne legyen notifyListeners, hanem külön a searchterm settere végén és külön a konstruktor végén legyen.

2023-12-09 16:59 UTC, Vini1424 approved these changes

2023-12-09 17:00 UTC, merged