Termék hozzáadás, áruház keresés
alxkovacs/Kovacs_Alex_Szakdolgozat pull request #15
Opened 2023-12-02 09:44 UTC by alxkovacs

2023-12-02 09:44 UTC, alxkovacs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Termék hozzáadása képernyő design és navigáció](https://trello.com/c/zRxfUDoa/26-term%C3%A9k-hozz%C3%A1ad%C3%A1sa-k%C3%A9perny%C5%91-design-%C3%A9s-navig%C3%A1ci%C3%B3)

2023-12-02 09:45 UTC, alxkovacs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Termék hozzáadás, áruház keresés üzleti logika](https://trello.com/c/Yl7XLchB/39-term%C3%A9k-hozz%C3%A1ad%C3%A1s-%C3%A1ruh%C3%A1z-keres%C3%A9s-%C3%BCzleti-logika)

2023-12-08 23:54 UTC, alxkovacs commented
![add_product_screen_android](https://github.com/alxkovacs/Kovacs_Alex_Szakdolgozat/assets/123123690/8ec418c1-2c55-4b41-8d1f-77847c8ac4eb)
![add_product_screen_ios](https://github.com/alxkovacs/Kovacs_Alex_Szakdolgozat/assets/123123690/23462f24-0795-4525-9eae-ef5715b0a2b7)
![store_search_screen_android](https://github.com/alxkovacs/Kovacs_Alex_Szakdolgozat/assets/123123690/cbc4670e-705a-4247-8e97-91ac4db19ec8)
![store_search_screen_ios](https://github.com/alxkovacs/Kovacs_Alex_Szakdolgozat/assets/123123690/41eeeb6b-68b5-4531-ace9-7c5819758179)

2023-12-09 17:01 UTC, Vini1424 requested changes
mehet a rebase és a self review

2023-12-09 21:58 UTC, Vini1424 commented on application/lib/view_model/store_search_screen_view_model.dart
> +    if (s.isEmpty) return s;
Van egy replaceFirst nevű extension, ami stringre hívható. Azzal egyszerűbben lehet az első betűt kapitalizálni. 
`s.replaceFirst(s[0], s[0]. toUpperCase()`

2023-12-10 15:30 UTC, Vini1424 approved these changes

2023-12-10 15:31 UTC, merged